version: '3.7'

services:
  db:
    image: postgres:12-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    entrypoint: emmett
    command: develop --host=0.0.0.0
    volumes:
      - ./tfstater:/app/app
    ports:
      - "8000:8000"
