{{ $postgresValues := .Values.postgresql }}
{{ $minioValues := .Values.minio }}
{{ $dbConfig := .Values.config.db }}
{{ $objStoreConfig := .Values.config.object_storage }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tfstater.fullname" . }}
  labels:
    {{- include "tfstater.labels" . | nindent 4 }}
type: Opaque
stringData:
  app.yml: |-
    db:
      {{- if $postgresValues.enabled }}
      host: {{ include "tfstater.postgresql.fullname" . }}
      {{- with $postgresValues }}
      database: {{ .postgresqlDatabase }}
      user: {{ .postgresqlUsername }}
      password: {{ .postgresqlPassword | quote }}
      {{- end }}
      {{- else }}
      {{- with $dbConfig }}
      host: {{ .host | quote }}
      database: {{ .database }}
      user: {{ .user }}
      password: {{ .password | quote }}
      {{- end }}
      {{- end }}
      pool_size: {{ $dbConfig.pool_size }}

    object_storage:
      {{- if $minioValues.enabled }}
      {{- $bucket := index $minioValues.buckets 0 }}
      endpoint: http://{{ include "tfstater.minio.fullname" . }}:{{ $minioValues.service.port }}
      access_key: {{ $minioValues.rootUser }}
      secret_key: {{ $minioValues.rootPassword | quote }}
      bucket: {{ $bucket.name }}
      {{- else }}
      endpoint: {{ $objStoreConfig.endpoint }}
      bucket: {{ $objStoreConfig.bucket }}
      region: {{ $objStoreConfig.region }}
      access_key: {{ $objStoreConfig.access_key }}
      secret_key: {{ $objStoreConfig.secret_key }}
      {{- end }}
      path_prefix: {{ $objStoreConfig.path_prefix | quote }}
      encrypt_data: {{ $objStoreConfig.encrypt_data }}

    {{ with .Values.config.auth -}}
    auth: {{ . | toYaml | nindent 6 }}
    {{- end }}

    {{ with .Values.config.smtp -}}
    smtp: {{ . | toYaml | nindent 6 }}
    {{- end }}

    {{ with .Values.config.idp -}}
    idp: {{ . | toYaml | nindent 6 }}
    {{- end }}
