name: Docker

on:
  push:
    tags:
      - '*.*.*'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v2

      - name: Get build version
        id: build_version
        run: |
          echo ::set-output name=version::${GITHUB_REF#refs/tags/}

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: "."
          push: true
          tags: ${{ env.REGISTRY }}/${{ github.repository }}:${{ steps.build_version.outputs.version }},${{ env.REGISTRY }}/${{ github.repository }}:latest
